export const API_ENDPOINTS = {
  // Public endpoints
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    refreshToken: '/auth/refresh',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    me: '/auth/me',
    verify2fa: '/auth/verify-2fa',
    changePassword: '/auth/change-password',
  },
  // Authenticated endpoints
  settings: {
    setup2fa: '/settings/2fa/setup',
    confirm2fa: '/settings/2fa/confirm',
    disable2fa: '/settings/2fa',
  },
  notifications: {
    list: '/notifications',
    markRead: (notificationId: string) => `/notifications/${notificationId}/read`,
    markAllRead: '/notifications/read-all',
  },
  auditLogs: {
    list: '/audit-logs',
  },
  platformAdmin: {
    dashboard: '/admin/dashboard',
    tenants: '/admin/tenants',
    tenantDetail: (tenantId: string) => `/admin/tenants/${tenantId}`,
    suspendTenant: (tenantId: string) => `/admin/tenants/${tenantId}/suspend`,
    reactivateTenant: (tenantId: string) => `/admin/tenants/${tenantId}/reactivate`,
    subscriptionPlans: '/subscription-plans/admin',
  },
  tenantRolePermissions: {
    workspace: '/tenant-role-permissions',
    assign: (roleId: string) => `/tenant-role-permissions/${roleId}`,
  },
  organization: {
    me: '/organization',
  },
  staff: {
    managers: '/managers',
    list: '/staff',
    detail: (userId: string) => `/staff/${userId}`,
    deactivate: (userId: string) => `/staff/${userId}/deactivate`,
    reactivate: (userId: string) => `/staff/${userId}/reactivate`,
    assignManager: (warehouseId: string) => `/warehouses/${warehouseId}/manager`,
    warehouseAssignments: (userId: string) => `/staff/${userId}/warehouses`,
  },
  warehouses: {
    list: '/warehouses',
    create: '/warehouses',
    detail: (warehouseId: string) => `/warehouses/${warehouseId}`,
    update: (warehouseId: string) => `/warehouses/${warehouseId}`,
    layout: (warehouseId: string) => `/warehouses/${warehouseId}/layout`,
    layoutScene: (warehouseId: string) => `/warehouses/${warehouseId}/layout/scene`,
    locations: (warehouseId: string) => `/warehouses/${warehouseId}/locations`,
    createZone: (warehouseId: string) => `/warehouses/${warehouseId}/zones`,
    updateZone: (warehouseId: string, zoneId: string) =>
      `/warehouses/${warehouseId}/zones/${zoneId}`,
    deactivateZone: (warehouseId: string, zoneId: string) =>
      `/warehouses/${warehouseId}/zones/${zoneId}/deactivate`,
    createRack: (warehouseId: string, zoneId: string) =>
      `/warehouses/${warehouseId}/zones/${zoneId}/racks`,
    updateRack: (warehouseId: string, zoneId: string, rackId: string) =>
      `/warehouses/${warehouseId}/zones/${zoneId}/racks/${rackId}`,
    deactivateRack: (warehouseId: string, zoneId: string, rackId: string) =>
      `/warehouses/${warehouseId}/zones/${zoneId}/racks/${rackId}/deactivate`,
    createSlot: (warehouseId: string, rackId: string) =>
      `/warehouses/${warehouseId}/racks/${rackId}/slots`,
    updateSlot: (warehouseId: string, rackId: string, slotId: string) =>
      `/warehouses/${warehouseId}/racks/${rackId}/slots/${slotId}`,
    deactivateSlot: (warehouseId: string, rackId: string, slotId: string) =>
      `/warehouses/${warehouseId}/racks/${rackId}/slots/${slotId}/deactivate`,
    locationBarcode: (warehouseId: string, locationType: string, locationId: string) =>
      `/warehouses/${warehouseId}/locations/${locationType.toLowerCase()}/${locationId}/barcode`,
    deactivate: (warehouseId: string) => `/warehouses/${warehouseId}/deactivate`,
  },
  inventory: {
    list: '/inventory',
    movements: '/inventory/movements',
    reservations: '/inventory/reservations',
    damaged: '/inventory/damaged',
    abcClassification: '/inventory/abc-classification',
    forecast: '/inventory/forecast',
    history: '/inventory/history',
  },
  cycleCounts: {
    list: '/cycle-counts',
    create: '/cycle-counts',
    detail: (cycleCountId: string) => `/cycle-counts/${cycleCountId}`,
    allowedActions: (cycleCountId: string) => `/cycle-counts/${cycleCountId}/allowed-actions`,
    recordItem: (cycleCountId: string, itemId: string) =>
      `/cycle-counts/${cycleCountId}/items/${itemId}`,
    submit: (cycleCountId: string) => `/cycle-counts/${cycleCountId}/submit`,
    recount: (cycleCountId: string) => `/cycle-counts/${cycleCountId}/recount`,
    finalize: (cycleCountId: string) => `/cycle-counts/${cycleCountId}/finalize`,
  },
  stockAdjustments: {
    list: '/stock-adjustments',
    create: '/stock-adjustments',
    detail: (adjustmentId: string) => `/stock-adjustments/${adjustmentId}`,
    allowedActions: (adjustmentId: string) => `/stock-adjustments/${adjustmentId}/allowed-actions`,
    approve: (adjustmentId: string) => `/stock-adjustments/${adjustmentId}/approve`,
    reject: (adjustmentId: string) => `/stock-adjustments/${adjustmentId}/reject`,
  },
  suppliers: {
    list: '/suppliers',
    create: '/suppliers',
    detail: (supplierId: string) => `/suppliers/${supplierId}`,
    update: (supplierId: string) => `/suppliers/${supplierId}`,
    deactivate: (supplierId: string) => `/suppliers/${supplierId}/deactivate`,
    reactivate: (supplierId: string) => `/suppliers/${supplierId}/reactivate`,
  },
  purchaseOrders: {
    list: '/purchase-orders',
    create: '/purchase-orders',
    detail: (purchaseOrderId: string) => `/purchase-orders/${purchaseOrderId}`,
    update: (purchaseOrderId: string) => `/purchase-orders/${purchaseOrderId}`,
    submit: (purchaseOrderId: string) => `/purchase-orders/${purchaseOrderId}/submit`,
    approve: (purchaseOrderId: string) => `/purchase-orders/${purchaseOrderId}/approve`,
    reject: (purchaseOrderId: string) => `/purchase-orders/${purchaseOrderId}/reject`,
    allowedActions: (purchaseOrderId: string) =>
      `/purchase-orders/${purchaseOrderId}/allowed-actions`,
  },
  inboundReceipts: {
    list: '/inbound-receipts',
    create: '/inbound-receipts',
    detail: (receiptId: string) => `/inbound-receipts/${receiptId}`,
    update: (receiptId: string) => `/inbound-receipts/${receiptId}`,
    receivingTasks: '/inbound-receipts/receiving-tasks',
    putawayTasks: '/inbound-receipts/putaway-tasks',
    submit: (receiptId: string) => `/inbound-receipts/${receiptId}/submit`,
    approve: (receiptId: string) => `/inbound-receipts/${receiptId}/approve`,
    reject: (receiptId: string) => `/inbound-receipts/${receiptId}/reject`,
    allowedActions: (receiptId: string) => `/inbound-receipts/${receiptId}/allowed-actions`,
    putaway: (receiptId: string) => `/inbound-receipts/${receiptId}/putaway`,
  },
  invitations: {
    send: '/invitations',
    accept: (token: string) => `/invitations/${token}/accept`,
    list: '/invitations',
    resend: (id: string) => `/invitations/${id}/resend`,
    revoke: (id: string) => `/invitations/${id}`,
  },
  subscription: {
    me: '/subscriptions/me',
    plans: '/subscription-plans',
    planById: (id: string) => `/subscription-plans/${id}`,
    upgrade: '/subscriptions/upgrade',
    renew: '/subscriptions/renew',
    cancel: '/subscriptions/me',
    paymentLink: '/subscriptions/payment-link',
    paymentStatus: (orderCode: string) => `/subscriptions/payments/${orderCode}/sync`,
  },
  public: {
    subscriptionPlans: '/public/subscription-plans',
    subscriptionFeatures: '/public/subscription-features',
  },
  units: {
    list: '/units',
  },
  categories: {
    list: '/categories',
  },
  products: {
    list: '/products',
    create: '/products',
    detail: (id: string) => `/products/${id}`,
    update: (id: string) => `/products/${id}`,
    stockPolicy: (id: string) => `/products/${id}/stock-policy`,
    barcode: (id: string) => `/products/${id}/barcode`,
    import: '/products/import',
  },
  payments: {
    history: '/payments',
    invoice: (paymentId: string) => `/payments/${paymentId}/invoice`,
    invoiceData: (paymentId: string) => `/payments/${paymentId}/invoice-data`,
  },
  transfers: {
    list: '/transfers',
    create: '/transfers',
    sourceWarehouses: '/transfers/source-warehouses',
    sourceInventory: '/transfers/source-inventory',
    detail: (transferId: string) => `/transfers/${transferId}`,
    approve: (transferId: string) => `/transfers/${transferId}/approve`,
    reject: (transferId: string) => `/transfers/${transferId}/reject`,
    dispatch: (transferId: string) => `/transfers/${transferId}/dispatch`,
    receive: (transferId: string) => `/transfers/${transferId}/receive`,
  },
  outboundOrders: {
    list: '/outbound-orders',
    create: '/outbound-orders',
    detail: (outboundOrderId: string) => `/outbound-orders/${outboundOrderId}`,
    issue: (outboundOrderId: string) => `/outbound-orders/${outboundOrderId}/issue`,
    returns: (outboundOrderId: string) => `/outbound-orders/${outboundOrderId}/returns`,
  },
  returns: {
    list: '/returns',
    detail: (returnId: string) => `/returns/${returnId}`,
    approve: (returnId: string) => `/returns/${returnId}/approve`,
    reject: (returnId: string) => `/returns/${returnId}/reject`,
  },
  deliveries: {
    list: '/deliveries',
    updateStatus: (outboundOrderId: string) => `/deliveries/${outboundOrderId}/status`,
  },
  customers: {
    list: '/customers',
    create: '/customers',
    detail: (customerId: string) => `/customers/${customerId}`,
    update: (customerId: string) => `/customers/${customerId}`,
    orderHistory: (customerId: string) => `/customers/${customerId}/orders`,
  },
} as const
