import type { Route } from 'next'

export const APP_ROUTES = {
  home: '/',
  pricing: '/pricing',
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verify2fa: '/auth/verify-2fa',
  },
  dashboard: '/dashboard',
  reports: '/reports' as Route,
  reportForecast: '/reports/forecast' as Route,
  myTasks: '/tasks' as Route,
  myTaskHistory: '/tasks/history' as Route,
  subscription: '/subscription',
  subscriptionPayments: '/subscription/payments',
  subscriptionInvoices: '/subscription/invoices',
  subscriptionPaymentResult: '/payment-result',
  organization: '/organization',
  staff: '/staff',
  staffImport: '/staff/import' as Route,
  invitations: {
    accept: '/invitations/accept',
  },
  dashboardByRole: {
    tenant: '/dashboard/tenant',
    manager: '/dashboard/manager',
    staff: '/dashboard/staff',
  },
  warehouses: '/warehouses',
  warehouseLayouts: '/warehouse-layouts' as Route,
  suppliers: '/suppliers',
  supplierImport: '/suppliers/import' as Route,
  units: '/units',
  unitImport: '/units/import' as Route,
  categories: '/categories',
  categoryImport: '/categories/import' as Route,
  supplierDetail: (supplierId: string) => `/suppliers/${supplierId}`,
  inboundRequests: '/inbound-requests',
  inboundRequestCreate: '/inbound-requests/new',
  inboundRequestDetail: (inboundRequestId: string) => `/inbound-requests/${inboundRequestId}`,
  inboundRequestEdit: (inboundRequestId: string) => `/inbound-requests/${inboundRequestId}/edit`,
  inbound: '/inbound',
  goodsReceipts: '/inbound/receipts',
  goodsReceiptDetail: (receiptId: string) => `/inbound/receipts/${receiptId}`,
  inboundPutaway: '/inbound/putaway',
  inboundPutawayDetail: (receiptId: string) => `/inbound/putaway/${receiptId}`,
  warehouseDetail: (warehouseId: string): Route => `/warehouses/${warehouseId}` as Route,
  warehouseLayout: (warehouseId: string) => `/warehouses/${warehouseId}/layout`,
  warehouseLayoutViewer: (warehouseId: string): Route =>
    `/warehouse-layouts/${warehouseId}` as Route,
  warehouseLayoutDesigner: (warehouseId: string): Route =>
    `/warehouse-layouts/${warehouseId}/designer` as Route,
  warehouseLocations: (warehouseId: string) => `/warehouses/${warehouseId}/locations`,
  warehouseLocationBarcode: (warehouseId: string, locationType: string, locationId: string) =>
    `/warehouses/${warehouseId}/locations/${locationType.toLowerCase()}/${locationId}/barcode`,
  inventory: '/inventory',
  inventoryMovements: '/inventory/movements',
  inventoryReservations: '/inventory/reservations',
  inventoryDamageCases: '/inventory/damage-cases',
  inventoryOpeningStocks: '/inventory/opening-stocks',
  inventoryAbcClassification: '/inventory/abc-classification',
  inventoryDiscrepancies: '/inventory/discrepancies',
  inventoryForecast: '/inventory/forecast', // Legacy URL redirects to reports/forecast.
  cycleCounts: '/inventory/cycle-counts',
  cycleCountCreate: '/inventory/cycle-counts/new',
  cycleCountDetail: (cycleCountId: string): Route =>
    `/inventory/cycle-counts/${cycleCountId}` as Route,
  stockAdjustments: '/inventory/stock-adjustments',
  stockAdjustmentDetail: (adjustmentId: string): Route =>
    `/inventory/stock-adjustments/${adjustmentId}` as Route,
  stockAdjustmentVoucherDetail: (voucherId: string): Route =>
    `/inventory/stock-adjustments/vouchers/${voucherId}` as Route,
  transfers: '/transfers',
  transfersTab: (stage: string): Route => `/transfers?tab=${stage}` as Route,
  /** Mở sẵn hộp thoại tạo công việc điều chuyển vị trí (điều chuyển nội bộ trong kho). */
  createRelocationTask: '/tasks?create=relocation' as Route,
  transferCreate: '/transfers/new',
  transferDetail: (transferId: string): Route => `/transfers/${transferId}` as Route,
  transferEdit: (transferId: string): Route => `/transfers/${transferId}/edit` as Route,
  transferPickTask: (transferId: string, shipmentId: string): Route =>
    `/tasks/transfers/${transferId}/shipments/${shipmentId}/pick` as Route,
  transferReceiveTask: (transferId: string, shipmentId: string): Route =>
    `/tasks/transfers/${transferId}/shipments/${shipmentId}/receive` as Route,
  stockIssueRequests: '/stock-issue-requests',
  stockIssueRequestCreate: '/stock-issue-requests/new',
  goodsReturnRequests: '/goods-return-requests',
  stockRecipients: '/stock-recipients',
  stockRecipientImport: '/stock-recipients/import' as Route,
  stockRecipientDetail: (stockRecipientId: string): Route =>
    `/stock-recipients/${stockRecipientId}` as Route,
  unauthorized: '/unauthorized',
  admin: {
    dashboard: '/admin/dashboard',
    tenants: '/admin/tenants',
    tenantDetail: (tenantId: string): Route => `/admin/tenants/${tenantId}` as Route,
    roles: '/admin/roles',
    subscriptionPlans: '/admin/subscription-plans',
    announcements: '/admin/announcements',
    payments: '/admin/payments',
  },
  products: '/products',
  productImport: '/products/import' satisfies Route,
  productDetail: (id: string) => `/products/${id}`,
  productCreate: '/products/create',
  profile: '/profile',
  notifications: '/notifications',
  auditLogs: '/audit-logs',
  settings: {
    security: '/settings/security',
    accessControl: '/settings/access-control',
  },
} as const
