import type { Route } from 'next'

export const APP_ROUTES = {
  home: '/',
  pricing: '/pricing',
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verify2fa: '/auth/verify-2fa',
  },
  dashboard: '/dashboard',
  subscription: '/subscription',
  subscriptionPayments: '/subscription/payments',
  subscriptionInvoices: '/subscription/invoices',
  subscriptionPaymentResult: '/subscription/payment-result',
  organization: '/organization',
  staff: '/staff',
  invitations: {
    accept: '/invitations/accept',
  },
  dashboardByRole: {
    tenant: '/dashboard/tenant',
    manager: '/dashboard/manager',
    staff: '/dashboard/staff',
  },
  warehouses: '/warehouses',
  suppliers: '/suppliers',
  supplierDetail: (supplierId: string) => `/suppliers/${supplierId}`,
  purchaseOrders: '/purchase-orders',
  purchaseOrderCreate: '/purchase-orders/new',
  purchaseOrderDetail: (purchaseOrderId: string) => `/purchase-orders/${purchaseOrderId}`,
  purchaseOrderEdit: (purchaseOrderId: string) => `/purchase-orders/${purchaseOrderId}/edit`,
  inbound: '/inbound',
  inboundReceipts: '/inbound/receipts',
  inboundReceiptDetail: (receiptId: string) => `/inbound/receipts/${receiptId}`,
  inboundPutaway: '/inbound/putaway',
  inboundPutawayDetail: (receiptId: string) => `/inbound/putaway/${receiptId}`,
  warehouseDetail: (warehouseId: string) => `/warehouses/${warehouseId}`,
  warehouseLayout: (warehouseId: string) => `/warehouses/${warehouseId}/layout`,
  warehouseLayoutDesigner: (warehouseId: string) => `/warehouses/${warehouseId}/layout/designer`,
  warehouseLocations: (warehouseId: string) => `/warehouses/${warehouseId}/locations`,
  warehouseLocationBarcode: (warehouseId: string, locationType: string, locationId: string) =>
    `/warehouses/${warehouseId}/locations/${locationType.toLowerCase()}/${locationId}/barcode`,
  inventory: '/inventory',
  inventoryMovements: '/inventory/movements',
  inventoryReservations: '/inventory/reservations',
  inventoryAbcClassification: '/inventory/abc-classification',
  inventoryForecast: '/inventory/forecast',
  cycleCounts: '/inventory/cycle-counts',
  cycleCountCreate: '/inventory/cycle-counts/new',
  cycleCountDetail: (cycleCountId: string): Route =>
    `/inventory/cycle-counts/${cycleCountId}` as Route,
  stockAdjustments: '/inventory/stock-adjustments',
  stockAdjustmentDetail: (adjustmentId: string): Route =>
    `/inventory/stock-adjustments/${adjustmentId}` as Route,
  transfers: '/transfers',
  transferCreate: '/transfers/new',
  orders: '/orders',
  orderCreate: '/orders/new',
  returns: '/returns',
  delivery: '/delivery',
  customers: '/customers',
  customerDetail: (customerId: string): Route => `/customers/${customerId}` as Route,
  unauthorized: '/unauthorized',
  admin: {
    roles: '/admin/roles',
    subscriptionPlans: '/admin/subscription-plans',
  },
  products: '/products',
  productDetail: (id: string) => `/products/${id}`,
  productCreate: '/products/create',
  profile: '/profile',
  settings: {
    security: '/settings/security',
    accessControl: '/settings/access-control',
  },
} as const
