import {
  ArrowLeftRight,
  ArrowUpRight,
  Building2,
  ChartColumn,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  History,
  LayoutDashboard,
  Lock,
  Package,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackageSearch,
  ReceiptText,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  TrendingUp,
  Truck,
  Undo2,
  User,
  Users,
  Warehouse,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const DefaultAiNavigationIcon: LucideIcon = ArrowUpRight

// Icon names come from WMS-Model's static route map (app/assistant/route_map.py).
export const AI_NAVIGATION_ICONS: Readonly<Record<string, LucideIcon>> = {
  'arrow-left-right': ArrowLeftRight,
  'building-2': Building2,
  'chart-column': ChartColumn,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'credit-card': CreditCard,
  history: History,
  'layout-dashboard': LayoutDashboard,
  lock: Lock,
  package: Package,
  'package-check': PackageCheck,
  'package-minus': PackageMinus,
  'package-open': PackageOpen,
  'package-search': PackageSearch,
  'receipt-text': ReceiptText,
  settings: Settings,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  'trending-up': TrendingUp,
  truck: Truck,
  'undo-2': Undo2,
  user: User,
  users: Users,
  warehouse: Warehouse,
}
