import { z } from 'zod'

export const reportColumnSchema = z.object({
  key: z.string(),
  label: z.string(),
  dataType: z.string(),
})
export const reportDefinitionSchema = z.object({
  type: z.string(),
  name: z.string(),
  group: z.string(),
  description: z.string(),
  usesPeriod: z.boolean(),
  requiresProduct: z.boolean(),
  columns: z.array(reportColumnSchema),
  formats: z.array(z.string()),
})
const commonRow = z.object({
  id: z.string(),
  warehouseId: z.string(),
  warehouseName: z.string(),
  productId: z.string().nullable(),
  sku: z.string(),
  productName: z.string(),
  unit: z.string(),
})
export const reportRowSchema = z.discriminatedUnion('rowType', [
  commonRow.extend({
    rowType: z.literal('replenishment'),
    onHand: z.number(),
    reserved: z.number(),
    available: z.number(),
    minimum: z.number(),
    target: z.number(),
    policyGap: z.number(),
    forecastSuggested: z.number().nullable(),
    forecastRunId: z.string().nullable(),
    forecastCompletedAt: z.string().nullable(),
    reason: z.string(),
  }),
  commonRow.extend({
    rowType: z.literal('slow-moving'),
    onHand: z.number(),
    lastExternalIssueAt: z.string().nullable(),
    daysWithoutIssue: z.number().nullable(),
    issuedInWindow: z.number(),
    signal: z.string(),
    reason: z.string(),
  }),
  commonRow.extend({
    rowType: z.literal('inbound-progress'),
    documentCode: z.string(),
    sourceName: z.string(),
    status: z.string(),
    createdAt: z.string(),
    requested: z.number(),
    received: z.number(),
    closed: z.number(),
    damaged: z.number(),
    putAway: z.number(),
    receivingRemaining: z.number(),
    putAwayRemaining: z.number(),
    sourceType: z.string(),
    sourceId: z.string(),
  }),
  commonRow.extend({
    rowType: z.literal('outbound-progress'),
    documentCode: z.string(),
    recipientName: z.string(),
    purpose: z.string().nullable(),
    status: z.string(),
    createdAt: z.string(),
    dispatchedAt: z.string().nullable(),
    requested: z.number(),
    activePicked: z.number(),
    issued: z.number(),
    reversed: z.number(),
    reserved: z.number(),
    sourceType: z.string(),
    sourceId: z.string(),
  }),
  commonRow.extend({
    rowType: z.literal('transfer-reconciliation'),
    documentCode: z.string(),
    sourceWarehouseName: z.string(),
    destinationWarehouseName: z.string(),
    status: z.string(),
    createdAt: z.string(),
    dispatchedAt: z.string().nullable(),
    receivedAt: z.string().nullable(),
    requested: z.number(),
    approved: z.number(),
    dispatched: z.number(),
    received: z.number(),
    damaged: z.number(),
    missing: z.number(),
    inTransit: z.number(),
    confirmedVariance: z.number(),
    sourceType: z.string(),
    sourceId: z.string(),
  }),
  commonRow.extend({
    rowType: z.literal('count-adjustment'),
    sourceType: z.string(),
    sourceId: z.string(),
    status: z.string(),
    createdAt: z.string(),
    slotCode: z.string(),
    systemQuantity: z.number().nullable(),
    countedQuantity: z.number().nullable(),
    difference: z.number().nullable(),
    recountRound: z.number().nullable(),
    adjustmentRequested: z.number().nullable(),
    postedNet: z.number().nullable(),
    reason: z.string().nullable(),
    reviewedBy: z.string().nullable(),
  }),
  commonRow.extend({
    rowType: z.literal('task-progress'),
    taskCode: z.string(),
    taskType: z.string(),
    status: z.string(),
    priority: z.string(),
    assigneeId: z.string().nullable(),
    assigneeName: z.string().nullable(),
    createdAt: z.string(),
    assignedAt: z.string().nullable(),
    startedAt: z.string().nullable(),
    dueAt: z.string().nullable(),
    completedAt: z.string().nullable(),
    deadlineState: z.string(),
    totalLines: z.number(),
    completedLines: z.number(),
    sourceType: z.string(),
    sourceId: z.string(),
  }),
  commonRow.extend({
    rowType: z.literal('inventory-balance'),
    openingBalance: z.number().nullable(),
    openingPosted: z.number(),
    externalIn: z.number(),
    externalOut: z.number(),
    transferIn: z.number(),
    transferOut: z.number(),
    adjustmentNet: z.number(),
    internalNet: z.number(),
    otherNet: z.number(),
    closingBalance: z.number().nullable(),
    historyStatus: z.string(),
  }),
  commonRow.extend({
    rowType: z.literal('inventory-snapshot'),
    zoneCode: z.string(),
    rackCode: z.string(),
    slotId: z.string(),
    slotCode: z.string(),
    lotNumber: z.string().nullable(),
    qualityStatus: z.string(),
    eligibilityStatus: z.string(),
    locationActive: z.boolean(),
    onHand: z.number(),
    reserved: z.number(),
    available: z.number(),
    unavailable: z.number(),
  }),
  commonRow.extend({
    rowType: z.literal('stock-card'),
    slotCode: z.string(),
    occurredAt: z.string(),
    movementType: z.string(),
    increase: z.number(),
    decrease: z.number(),
    stockKeyBalanceAfter: z.number(),
    performedBy: z.string(),
    referenceType: z.string(),
    referenceId: z.string(),
    correctsMovementId: z.string().nullable(),
    sourceType: z.string().nullable(),
    sourceId: z.string().nullable(),
  }),
])
export const reportResponseSchema = z.object({
  reportType: z.string(),
  schemaVersion: z.string(),
  generatedAt: z.string(),
  timeBasis: z.string(),
  dataQuality: z.string(),
  warnings: z.array(z.string()),
  appliedFilters: z.object({
    warehouseIds: z.array(z.string()),
    dateFrom: z.string().nullable(),
    dateTo: z.string().nullable(),
    productId: z.string().nullable(),
    search: z.string().nullable(),
    status: z.string().nullable(),
    assigneeId: z.string().nullable(),
    taskType: z.string().nullable(),
    deadline: z.string().nullable(),
  }),
  columns: z.array(reportColumnSchema),
  items: z.array(reportRowSchema),
  totalCount: z.number(),
  pageNumber: z.number(),
  pageSize: z.number(),
})
export const reportOptionsSchema = z.object({
  warehouses: z.array(z.object({ id: z.string(), name: z.string() })),
  products: z.array(
    z.object({ id: z.string(), sku: z.string(), name: z.string(), unit: z.string() })
  ),
  productsTruncated: z.boolean(),
  assignees: z.array(z.object({ id: z.string(), name: z.string() })),
})
export const reportFilterSchema = z
  .object({
    warehouseId: z.string(),
    productId: z.string(),
    search: z.string().max(100, 'Từ khóa tối đa 100 ký tự.'),
    status: z.string(),
    assigneeId: z.string(),
    taskType: z.string(),
    deadline: z.string(),
    allDates: z.boolean(),
    dateFrom: z.iso.date('Ngày bắt đầu không hợp lệ.'),
    dateTo: z.iso.date('Ngày kết thúc không hợp lệ.'),
  })
  .refine((values) => values.dateFrom <= values.dateTo, {
    message: 'Ngày bắt đầu phải trước hoặc bằng ngày kết thúc.',
    path: ['dateTo'],
  })
export type ReportDefinition = z.infer<typeof reportDefinitionSchema>
export type ReportColumn = z.infer<typeof reportColumnSchema>
export type ReportRow = z.infer<typeof reportRowSchema>
export type WarehouseReport = z.infer<typeof reportResponseSchema>
export type ReportOptions = z.infer<typeof reportOptionsSchema>
export type ReportFilterValues = z.infer<typeof reportFilterSchema>
