export { default as InboundReceivingPage } from './InboundReceivingPage'
export { default as GoodsReceiptsPage } from './GoodsReceiptsPage'
export { default as GoodsReceiptDetailPage } from './GoodsReceiptDetailPage'
export { default as InboundPutawayPage } from './InboundPutawayPage'
export { default as InboundPutawayDetailPage } from './InboundPutawayDetailPage'
