export { default as InboundReceivingPage } from './InboundReceivingPage'
export { default as InboundReceiptsPage } from './InboundReceiptsPage'
export { default as InboundReceiptDetailPage } from './InboundReceiptDetailPage'
export { default as InboundPutawayPage } from './InboundPutawayPage'
export { default as InboundPutawayDetailPage } from './InboundPutawayDetailPage'
