const labels: Record<string, string> = {
  NoIssueInWindow: 'Không có xuất trong cửa sổ',
  HasIssueInWindow: 'Có xuất trong cửa sổ',
  Good: 'Tốt',
  Damaged: 'Hỏng',
  Available: 'Có thể sử dụng',
  InspectionHold: 'Chờ kiểm tra',
  DamageHold: 'Giữ xử lý hỏng',
  Quarantine: 'Cách ly',
  PutAway: 'Cất hàng',
  Receiving: 'Nhận hàng',
  CycleCount: 'Kiểm kê',
  Relocation: 'Chuyển vị trí',
  TransferPick: 'Lấy hàng điều chuyển',
  TransferReceive: 'Nhận hàng điều chuyển',
  AwaitingResolution: 'Chờ xử lý chênh lệch',
  Pick: 'Lấy hàng nội bộ',
  Issue: 'Xuất kho',
  TransferOut: 'Chuyển đi',
  TransferIn: 'Chuyển đến',
  Opening: 'Khai báo tồn đầu',
  Reclassification: 'Đổi phân loại',
  Adjustment: 'Điều chỉnh',
  Correction: 'Sửa biến động',
  ReturnIn: 'Nhập trả lại',
  Scrap: 'Loại bỏ',
  Draft: 'Bản nháp',
  Pending: 'Chờ xử lý',
  PendingApproval: 'Chờ duyệt',
  Approved: 'Đã duyệt',
  Rejected: 'Từ chối',
  Sent: 'Đã gửi',
  Confirmed: 'Đã xác nhận',
  PartiallyReceived: 'Đã nhận một phần',
  Received: 'Đã nhận đủ',
  Closed: 'Đã đóng',
  InspectionCorrectionRequired: 'Cần sửa kiểm hàng',
  PendingSourceApproval: 'Chờ kho nguồn duyệt',
  InTransit: 'Đang chuyển',
  ReceivedWithVariance: 'Đã nhận có chênh lệch',
  ReleasedForPicking: 'Được phép lấy',
  Picking: 'Đang lấy',
  Picked: 'Đã lấy đủ',
  AuthorizedForDispatch: 'Được phép xuất',
  Dispatched: 'Đã xuất',
  Queued: 'Chờ bắt đầu',
  InProgress: 'Đang xử lý',
  Paused: 'Tạm dừng',
  Completed: 'Hoàn tất',
  Cancelled: 'Đã hủy',
  Scheduled: 'Đã lên lịch',
  Counting: 'Đang đếm',
  Submitted: 'Đã gửi kết quả',
  Recount: 'Đếm lại',
  Low: 'Thấp',
  Normal: 'Bình thường',
  High: 'Cao',
  Urgent: 'Khẩn',
  Overdue: 'Quá hạn',
  DueSoon: 'Sắp đến hạn (2 giờ)',
  NoDeadline: 'Chưa đặt hạn',
  OnTrack: 'Còn hạn',
  Terminal: 'Đã kết thúc',
  StockAdjustment: 'Yêu cầu điều chỉnh',
  ReconciledJournal: 'Nhật ký đã đối soát',
  InsufficientHistory: 'Chưa đủ lịch sử',
}
export function reportStatusLabel(value: string): string {
  return labels[value] ?? value
}
